PsihoKorak Platforma/PsihoKorak Platforma/Models/Psychologist.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PsihoKorak_Platforma.Models;

public partial class Psychologist
{
    public int PsychologistId { get; set; }

    public string Email { get; set; }

    public string HashedPassword { get; set; }

    public string PasswordSalt { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public virtual ICollection<Help> Helps { get; set; } = new List<Help>();
}

PsihoKorak Platforma/PsihoKorak Platforma/Models/Session.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PsihoKorak_Platforma.Models;

public partial class Session
{
    public int SessionId { get; set; }

    public DateTime DateTime { get; set; }

    public TimeSpan Duration { get; set; }

    public int SessionTypeId { get; set; }

    public virtual ICollection<Help> Helps { get; set; } = new List<Help>();

    public virtual SessionType SessionType { get; set; }
}

PsihoKorak Platforma/PsihoKorak Platforma/Models/SessionType.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PsihoKorak_Platforma.Models;

public partial class SessionType
{
    public int SessionTypeId { get; set; }

    public string SessionTypeName { get; set; }

    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();
}

PsihoKorak Platforma/PsihoKorak Platforma/ViewModels/LoginViewModel.cs
namespace PsihoKorak_Platforma.ViewModels
{
    public class LoginViewModel
    {
        public required string Email { get; set; }
        public required string Password { get; set; }
    }
}

PsihoKorak Platforma/PsihoKorak Platforma/Controllers/PsychologistController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PsihoKorak_Platforma.Models;
using PsihoKorak_Platforma.Utils;
using PsihoKorak_Platforma.ViewModels;
using System.Text.RegularExpressions;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace PsihoKorak_Platforma.Controllers
{
    public class PsychologistController : Controller
    {
        private readonly PsihoKorakPlatformaContext? ctx;

        public PsychologistController(PsihoKorakPlatformaContext ctx)
        {
            this.ctx = ctx;
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("Id") == null)
            {
                return RedirectToAction("Login");
            }

            Response.Headers.Add("Cache-Control", "no-cache, no-store, must-revalidate");
            Response.Headers.Add("Pragma", "no-cache");
            Response.Headers.Add("Expires", "0");

            if (int.TryParse(HttpContext.Session.GetString("Id"), out int psychologistId))
            {
                var query = ctx.Sessions.AsNoTracking()
                                        .Where(s => s.Helps.Any(h => h.PsychologistId == psychologistId))
                                        .Include(s => s.SessionType)
                                        .ToList();

                var sessions = query.Select(s => new MDViewModel
                {
                    SessionId = s.SessionId,
                    DateTime = s.DateTime.ToString(),
                    Duration = s.Duration.ToString(),
                    Helps = s.Helps,
                    SessionType = s.SessionType.SessionTypeName
                }).ToList();

                var model = new ListMDViewModel
                {
                    Md = sessions,
                };

                return View(model);
            }
            else
            {
                return BadRequest();
            }
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LoginPsychologist(String Email, String Password)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Error"] = "Invalid data.";
                return View("Login");
            }

            var psychologist = await ctx.Psychologists.AsNoTracking()
                                                      .FirstOrDefaultAsync(p => p.Email == Email);
            
            if (psychologist != null)
            {
                string hashedPassword = CryptoUtils.HashPassword(Password, Convert.FromBase64String(psychologist.PasswordSalt));
                if (psychologist.HashedPassword.Equals(hashedPassword, StringComparison.Ordinal))
                {
                    HttpContext.Session.SetString("FirstName", psychologist.FirstName);
                    HttpContext.Session.SetString("LastName", psychologist.LastName);
                    HttpContext.Session.SetString("Id", psychologist.PsychologistId.ToString());

                    return RedirectToAction("Index");
                }
            }

            ViewData["Error"] = "Wrong email or password";
            return View("Login");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            HttpContext.Response.Cookies.Append("SessionName", "", new CookieOptions
            {
                Expires = DateTime.Now.AddDays(-1)
            });
            HttpContext.Response.Cookies.Delete("SessionName");

            return View("Login");
        }

        public IActionResult Register()
        {
            HttpContext.Session.Clear();
            HttpContext.Response.Cookies.Append("SessionName", "", new CookieOptions
            {
                Expires = DateTime.Now.AddDays(-1)
            });
            HttpContext.Response.Cookies.Delete("SessionName");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterPsychologist(String FirstName, String LastName, String Email, String Password)
        {
            if(String.IsNullOrWhiteSpace(Email) || !Regex.IsMatch(Email, @"^[^@\s]+@[^@\s]+\.[^@\s]+$"))
            {
                ViewData["Error"] = "Invalid email format";
                return View("Register");
            }

            var psythologistToCheck = await ctx.Psychologists.AsNoTracking()
                                                             .FirstOrDefaultAsync(p => p.Email == Email);

            if (psythologistToCheck != null)
            {
                ViewData["Error"] = "Email is already in use";
                return View("Register");
            }

            if (String.IsNullOrWhiteSpace(Password) || Password.Length < 8 || !Regex.IsMatch(Password, @"[A-Z]") ||
                                                                              !Regex.IsMatch(Password, @"[a-z]") ||
                                                                              !Regex.IsMatch(Password, @"[0-9]") ||
                                                                              !Regex.IsMatch(Password, @"[\W_]"))
            {
                ViewData["Error"] = "Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one number, and one special character";
                return View("Register");
            }

            var salt = CryptoUtils.GetSalt();
            var hashedPassword = CryptoUtils.HashPassword(Password, salt);

            var newPsychologist = new Psychologist
            {
                Email = Email,
                HashedPassword = hashedPassword,
                PasswordSalt = Convert.ToBase64String(salt),
                FirstName = FirstName,
                LastName = LastName
            };

            try
            {
                await ctx.Psychologists.AddAsync(newPsychologist);
                await ctx.SaveChangesAsync();

                HttpContext.Session.SetString("FirstName", newPsychologist.FirstName);
                HttpContext.Session.SetString("LastName", newPsychologist.LastName);
                HttpContext.Session.SetString("Id", newPsychologist.PsychologistId.ToString());

                return RedirectToAction("Index");
            }
            catch
            {
                ViewData["Error"] = "Error with registration";
                return View("Register");
            }
        }

        [HttpPost]
        public IActionResult FilterSessionsByType(String SessionType)
        {
            if (int.TryParse(HttpContext.Session.GetString("Id"), out int psychologistId))
            {
                var query = ctx.Sessions.AsNoTracking()
                                        .Where(s => s.Helps.Any(h => h.PsychologistId == psychologistId))
                                        .Where(s => s.SessionType.SessionTypeName.Contains(SessionType))
                                        .Include(s => s.SessionType)
                                        .ToList();

                var sessions = query.Select(s => new MDViewModel
                {
                    SessionId = s.SessionId,
                    DateTime = s.DateTime.ToString(),
                    Duration = s.Duration.ToString(),
                    Helps = s.Helps,
                    SessionType = s.SessionType.SessionTypeName
                }).ToList();

                var model = new ListMDViewModel
                {
                    Md = sessions,
                };

                return View("Index", model);
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            if (HttpContext.Session.GetString("Id") == null)
            {
                return RedirectToAction("Login");
            }

            await PrepareDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSession(DateTime Date, int Duration, String SessionTypeId)
        {
            try
            {
                Session newSession = new Session
                {
                    DateTime = Date,
                    Duration = TimeSpan.FromMinutes(Duration),
                    SessionTypeId = int.Parse(SessionTypeId)
                };

                ctx.Sessions.Add(newSession);
                await ctx.SaveChangesAsync();

                var lastSession = await ctx.Sessions
                                           .OrderByDescending(s => s.SessionId) 
                                           .FirstOrDefaultAsync();

                var newHelp = new Help
                {
                    PatientId = null,
                    SessionId = lastSession.SessionId,
                    PsychologistId = int.Parse(HttpContext.Session.GetString("Id"))
                };

                ctx.Helps.Add(newHelp);
                await ctx.SaveChangesAsync();

                var query = ctx.Sessions.AsNoTracking()
                                        .Where(s => s.Helps.Any(h => h.PsychologistId == int.Parse(HttpContext.Session.GetString("Id"))))
                                        .Include(s => s.SessionType)
                                        .ToList();

                var sessions = query.Select(s => new MDViewModel
                {
                    SessionId = s.SessionId,
                    DateTime = s.DateTime.ToString(),
                    Duration = s.Duration.ToString(),
                    Helps = s.Helps,
                    SessionType = s.SessionType.SessionTypeName
                }).ToList();

                var model = new ListMDViewModel
                {

PsihoKorak Platforma/PsihoKorak Platforma/Views/Psychologist/Create.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "Create";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/create.css" />
    <title>@ViewData["Title"]</title>
</head>

<body>
    <header class="header-container">
        <div class="header-content">
            <button type="button" class="logout" onclick="location.href='@Url.Action("Index", "PSychologist")'">Home</button>
            <button type="button" class="logout" onclick="location.href='@Url.Action("SessionTypes", "Psychologist")'">Session types</button>
            <h1 class="display-4">@Accessor.HttpContext.Session.GetString("FirstName") @Accessor.HttpContext.Session.GetString("LastName")</h1>
            <button type="button" class="logout" onclick="location.href='@Url.Action("Logout", "Psychologist")'">Log out</button>
        </div>
    </header>

    <div class="container">
        <form action="@Url.Action("CreateSession", "Psychologist")" method="post">
            @Html.AntiForgeryToken()
            <h1>New session</h1>
            <div>
                <label for="Date" class="form-label">Date and time</label>
                <input name="Date" class="form-control" type="datetime-local"/>
            </div>
            <div>
                <label for="Duration" class="form-label">Duration in minutes</label>
                <input name="Duration" class="form-control" type="number" min="0"/>
            </div>
            <div>
                <label class="form-label">Tip sesije</label>
                <select class="form-control" name="SessionTypeId" >
                    <option disabled selected value="">Choose session type</option>
                    @foreach (var sessionType in ViewBag.SessionItems)
                    {
                        <option value="@sessionType.Value">@sessionType.Text</option>
                    }
                </select>
            </div>
            <div>
                <button type="submit">Create new session</button>
            </div>
        </form>
        <div class="error-message">@ViewData["Error"]</div>
    </div>
</body>

PsihoKorak Platforma/PsihoKorak Platforma/Views/Psychologist/Detail.cshtml
@model PsihoKorak_Platforma.ViewModels.DetailMasterDetailViewModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "Home Page";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/index.css" />
    <title>@ViewData["Title"]</title>
</head>

<body>
    <header class="header-container">
        <div class="header-content">
            <button type="button" class="logout" onclick="location.href='@Url.Action("Index", "PSychologist")'">Home</button>
            <button type="button" class="logout" onclick="location.href='@Url.Action("SessionTypes", "Psychologist")'">Session types</button>
            <h1 class="display-4">@Accessor.HttpContext.Session.GetString("FirstName") @Accessor.HttpContext.Session.GetString("LastName")</h1>
            <button type="button" class="logout" onclick="location.href='@Url.Action("Logout", "Psychologist")'">Log out</button>
        </div>
    </header>
    
    <hr />

    <h5>Add new Detail</h5>
    <div class="add-detail-container">
        <form action="@Url.Action("CreateHelp", "Psychologist")" method="post">
            @Html.AntiForgeryToken()
            <div>
                <label for="Note" class="form-label">Note</label>
                <input name="Note" class="form-control" />
            </div>
            <div>
                <label class="form-label">Patient</label>
                <select class="form-control" name="PatientId">
                    <option disabled selected value="">Choose patient</option>
                    @foreach (var patient in Model.Patients)
                    {
                        <option value="@patient.PatientId">@patient.FirstName @patient.LastName</option>
                    }
                </select>
            </div>
            <input type="hidden" name="SessionId" value="@Model.Sessions.SessionId" />
            <div>
                <button type="submit">Create new detail</button>
            </div>
        </form>
    </div>

    <hr />

    <h5>Search by Patient</h5>
    <div class="search-container">
        <form action="@Url.Action("FilterByPatient", "Psychologist")" method="post">
            <label for="PatientName" class="form-label">Patient Name</label>
            <input name="PatientName" class="form-control" />
            <input type="hidden" name="SessionId" value="@Model.Sessions.SessionId" />
            <button type="submit">Search</button>
        </form>
    </div>

    <hr />

    <div class="table-container">
        <h5>Details in session</h5>
        <table>
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Note
                    </th>
                    <th>
                        Patient
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var help in Model.Helps)
                {
                    <tr>
                        <td>@help.HelpsId</td>
                        <td>@help.Note</td>
                        <td>@help.PatientName</td>
                        <td>
                            <form action="@Url.Action("DetailUpdate", "Psychologist")" method="post">
                                <input type="hidden" name="HelpsId" value="@help.HelpsId" />
                                <button type="submit">Update</button>
                            </form>

                            <form action="@Url.Action("DeleteHelp", "Psychologist")" method="post">
                                <input type="hidden" name="HelpsId" value="@help.HelpsId" />
                                <button type="submit">Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>

PsihoKorak Platforma/PsihoKorak Platforma/Views/Psychologist/DetailUpdate.cshtml
@model PsihoKorak_Platforma.ViewModels.HelpsViewModelHelper
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "Update";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/create.css" />
    <title>@ViewData["Title"]</title>
</head>

<body>
    <header class="header-container">
        <div class="header-content">
            <button type="button" class="logout" onclick="location.href='@Url.Action("Index", "PSychologist")'">Home</button>
            <button type="button" class="logout" onclick="location.href='@Url.Action("SessionTypes", "Psychologist")'">Session types</button>
            <h1 class="display-4">@Accessor.HttpContext.Session.GetString("FirstName") @Accessor.HttpContext.Session.GetString("LastName")</h1>
            <button type="button" class="logout" onclick="location.href='@Url.Action("Logout", "Psychologist")'">Log out</button>
        </div>
    </header>

    <div class="container">
        <form action="@Url.Action("UpdateHelp", "Psychologist")" method="post">
            @Html.AntiForgeryToken()
            <h1>Update Detail</h1>
            <div>
                <label for="HelpsId" class="form-label">HelpsId</label>
                <input name="HelpsId" type="hidden" value="@Model.HelpsId" />
                <input name="DisplayHelpsId" class="form-control" disabled value="@Model.HelpsId" />
            </div>
            <div>
                <label for="Note" class="form-label">Note</label>
                <input name="Note" class="form-control" type="text" value="@Model.Note" />
            </div>
            <div>
                <label class="form-label">Patient</label>
                <select class="form-control" name="PatientId">
                    <option disabled selected value="">Choose patient</option>
                    @foreach (var patient in ViewBag.Patients)
                    {
                        <option value="@patient.Value">@patient.Text</option>
                    }
                </select>
            </div>
            <div>
                <button type="submit">Update session</button>
            </div>
        </form>
        <div class="error-message">@ViewData["Error"]</div>
    </div>
</body>

PsihoKorak Platforma/PsihoKorak Platforma/Views/Psychologist/Index.cshtml
@model PsihoKorak_Platforma.ViewModels.ListMDViewModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "Home Page";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/index.css" />
    <title>@ViewData["Title"]</title>
</head>

<body>
    <header class="header-container">
        <div class="header-content">
            <button type="button" class="logout" onclick="location.href='@Url.Action("Index", "PSychologist")'">Home</button>
            <button type="button" class="logout" onclick="location.href='@Url.Action("SessionTypes", "Psychologist")'">Session types</button>
            <h1 class="display-4">@Accessor.HttpContext.Session.GetString("FirstName") @Accessor.HttpContext.Session.GetString("LastName")</h1>
            <button type="button" class="logout" onclick="location.href='@Url.Action("Logout", "Psychologist")'">Log out</button>
        </div>
    </header>

    <div class="search-container">
        <form method="post" action="@Url.Action("FilterSessionsByType", "Psychologist")">
            <label for="searchSessionType">Search by Session Type:</label>
            <input type="text" name="SessionType">
            <button type="submit">Search</button>
        </form>
    </div>
    <div class="table-container">
        <button type="button" onclick="location.href='@Url.Action("Create", "Psychologist")'">Create new session</button>
        <table>
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Date and time
                    </th>
                    <th>
                        Duration
                    </th>
                    <th>
                        Session type
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var session in Model.Md)
                {
                    <tr>
                        <td>@session.SessionId</td>
                        <td>@session.DateTime</td>
                        <td>@session.Duration</td>
                        <td>@session.SessionType</td>
                        <td>
                            <form action="@Url.Action("Detail", "Psychologist")" method="post">
                                <input type="hidden" name="SessionId" value="@session.SessionId" />
                                <button type="submit">Detail</button>
                            </form>
                            <form action="@Url.Action("Update", "Psychologist")" method="post">
                                <input type="hidden" name="SessionId" value="@session.SessionId" />
                                <button type="submit">Update</button>
                            </form>

                            <form action="@Url.Action("DeleteSession", "Psychologist")" method="post">
                                <input type="hidden" name="SessionId" value="@session.SessionId"/>
                                <button type="submit" >Delete</button>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>

PsihoKorak Platforma/PsihoKorak Platforma/Views/Psychologist/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/login.css" />
    <title>@ViewData["Title"]</title>
</head>

<body>
    <div class="login-box">
        <form action="@Url.Action("LoginPsychologist", "Psychologist")" method="post">
            @Html.AntiForgeryToken()
            <h1>PsihoKorak Platforma</h1>
            <div>
                <label for="Email" class="form-label">Email</label>
                <input name="Email" class="form-control" type="email" autocomplete="email" placeholder="Enter your email" />
            </div>
            <div>
                <label for="Password" class="form-label">Password</label>
                <input name="Password" class="form-control" type="password" autocomplete="current-password" placeholder="Enter your password" />
            </div>
            <div>
                <button type="submit">Login</button>
            </div>
        </form>
        <div class="error-message">@ViewData["Error"]</div>
        <div class="center">
            <button type="button" onclick="location.href='@Url.Action("Register", "Psychologist")'">Register instead</button>
        </div>
    </div>
</body>

PsihoKorak Platforma/PsihoKorak Platforma/Views/Psychologist/Register.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering

@{
    ViewData["Title"] = "Register";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/login.css" />
    <title>@ViewData["Title"]</title>
</head>

<body>
    <div class="login-box">
        <form action="@Url.Action("RegisterPsychologist", "PSychologist")" method="post">
            @Html.AntiForgeryToken() 
            <h1>PsihoKorak Platforma</h1>
            <div>
                <label for="FirstName" class="form-label">First name</label>
                <input name="FirstName" class="form-control"/>
            </div>
            <div>
                <label for="LastName" class="form-label">Last name</label>
                <input name="LastName" class="form-control"/>
            </div>
            <div>
                <label for="Email" class="form-label">Email</label>
                <input name="Email" class="form-control" type="email"/>
            </div>
            <div>
                <label for="Password" class="form-label">Password</label>
                <input name="Password" class="form-control" type="password"/>
            </div>
            <div>
                <button type="submit">Register</button>
            </div>
        </form>
        <div class="error-message">@ViewData["Error"]</div>
        <div class="center">
            <button type="button" onclick="location.href='@Url.Action("Login", "Psychologist")'">Login instead</button>
        </div>
    </div>
</body>

PsihoKorak Platforma/PsihoKorak Platforma/Views/Psychologist/SessionTypeUpdate.cshtml
@model PsihoKorak_Platforma.ViewModels.SessionTypeViewModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor

@{
    ViewData["Title"] = "Update";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/create.css" />
    <title>@ViewData["Title"]</title>
</head>

<body>
    <header class="header-container">
        <div class="header-content">
            <button type="button" class="logout" onclick="location.href='@Url.Action("Index", "PSychologist")'">Home</button>
            <button type="button" class="logout" onclick="location.href='@Url.Action("SessionTypes", "Psychologist")'">Session types</button>
            <h1 class="display-4">@Accessor.HttpContext.Session.GetString("FirstName") @Accessor.HttpContext.Session.GetString("LastName")</h1>
            <button type="button" class="logout" onclick="location.href='@Url.Action("Logout", "Psychologist")'">Log out</button>
        </div>
    </header>

    <div class="container">
        <form action="@Url.Action("UpdateSessionType", "Psychologist")" method="post">
            @Html.AntiForgeryToken()
            <h1>Update session type</h1>
            <div>
                <label for="SessionTypeId" class="form-label">SessionTypeId</label>
                <input name="SessionTypeId" type="hidden" value="@Model.SessionTypeId" />
                <input name="DisplaySessionTypeId" class="form-control" disabled value="@Model.SessionTypeId" />
            </div>
            <div>
                <label for="SessionTypeName" class="form-label">Name</label>
                <input name="SessionTypeName" class="form-control" type="text" value="@Model.SessionTypeName" />
            </div>
            <div>
                <button type="submit">Update session type</button>
            </div>
        </form>
        <div class="error-message">@ViewData["Error"]</div>
    </div>
</body>